Feat/ansible results db
dnum-mi/dso-console pull request #117
Opened 2022-12-20 13:36 UTC by ArnaudTa

J'ai besoin d'aide pour écrire les tests si vous avez du temps dans la semaine

2022-12-20 14:28 UTC, baudointran commented on apps/ansible-api/src/ansible.js
> +      reject()
Il faudra un "return" si non le suivant va s’exécuter

2022-12-20 14:28 UTC, baudointran commented on apps/ansible-api/src/ansible.js
> +      resolve()
idem

2022-12-20 15:13 UTC, ArnaudTa commented on apps/ansible-api/src/ansible.js
> +      reject()
bien vu c'est un if qui return !

2022-12-20 15:16 UTC, ArnaudTa commented on apps/ansible-api/src/ansible.js
> +      resolve()
cependant sur celui-là je ne vois pas le besoin de return l'appel de fonction, on est dans la callback et il n'y a rien après ce if

2022-12-21 09:49 UTC, baudointran requested changes

2022-12-21 09:49 UTC, baudointran commented on apps/server/src/controllers/project.js
> +  data.status = 'initializing'
Mettre la valeur dans un fichier regroupant les constants ou valeur de référence

2022-12-21 09:49 UTC, baudointran commented on apps/server/src/controllers/project.js
> +        project.status = 'created'
idem

2022-12-21 09:49 UTC, baudointran commented on apps/server/src/controllers/project.js
> +        project.status = 'failed'
idem

2022-12-21 09:49 UTC, baudointran commented on packages/shared/src/schemas/project.js
> +
A mettre dans un fichier regroupement des valeurs de reférences pour le project et pouvoir utiliser ce fichier dans le apps/server/src/controllers/project.js 

exemple  contenu devra avoir:
export const INITIALIZING = 'initializing'
....
....

export const status = [
 INITIALIZING,
....
...
]

2022-12-21 10:02 UTC, baudointran requested changes

2022-12-21 10:02 UTC, baudointran commented on apps/ansible-api/src/controllers/project.js
> +      })
runPlaybook est un fonction qui retourne un Promise.
si vous utilisez await, le then et catch n'est plus utilisable. les valeurs de resolve sont renvoyé comme retour de la fonction et les valeurs de reject sont envoyés dans comme une erreur qui seront capturé par le catch du try.

Si vous utilisez le then().catch() pour la fonction , il faut retirer le await

2022-12-21 13:55 UTC, clairenollet commented on apps/server/src/controllers/project.js
> +  data.status = 'initializing'
A priori dans `packages/shared/src/schemas/project.js`

2022-12-21 17:43 UTC, ArnaudTa commented on apps/server/src/controllers/project.js
> +  data.status = 'initializing'
hésitez pas à commiter, je suis mauvais en organisation de code source, je balance le POC de la PR

2023-01-07 01:25 UTC, ArnaudTa commented on apps/ansible-api/src/controllers/project.js
> +      })
enfin corrigé ! j'ai réécrit tous les commits de la branche

2023-01-07 01:36 UTC, ArnaudTa commented
Les tests cypress ne passent pas, sûrement à cause du composant que j'ai ajouté mais j'y comprends rien

2023-01-07 01:42 UTC, ArnaudTa commented
Il faut faire bien gaffe au fichier maintenance.js, il permet de requeter et d'updater en ligne de commande sur la BDD, 
Aussi comme j'en ai un peu marre d'avoir des clés optionnels en BDD qui posent des problèmes lorsque le tout est envoyé aux playbooks, au démarrage de l'appli une moulinette se charge de renseigner toutes ses propriétés.
Pareil pour le status du projet il passe en "created" si rien n'était renseigné.

J'ai pas trouvé (ni chercher) de manière mettre des valeurs par défaut dans le json avec sequelize...

2023-01-19 19:10 UTC, closed without merging