Feat/administration
dnum-mi/dso-console pull request #303
Opened 2023-03-22 09:41 UTC by this-is-tobi

2023-04-07 13:53 UTC, this-is-tobi commented on apps/client/src/utils/keycloak/keycloak.js
> +    console.log(keycloak)
Un `console.log` à supprimer

2023-04-07 13:57 UTC, this-is-tobi commented on apps/client/src/views/admin/ListUser.vue
> +  // 'Administrateur',
Des commentaires à supprimer ?

2023-04-07 14:05 UTC, this-is-tobi commented on apps/server/src/utils/exceptions.js
> +}
Y'a-t-il ici une raison de créer une `class` ?

2023-04-07 14:10 UTC, this-is-tobi commented on apps/client/src/router/index.js
> +    }
Je ne suis pas sûr que le `try / catch` soit utile ici (pas d'opération asynchrone qui pourrait échouer à priori

2023-04-07 14:10 UTC, this-is-tobi commented on apps/client/src/stores/project.js
> +  // }
A supprimer

2023-04-07 14:20 UTC, LouisGongora commented on apps/server/src/utils/exceptions.js
> +}
Ca me semble logique pour créer une Exception custom
Peut-être un autre moyen en js ?

2023-04-07 14:38 UTC, LouisGongora commented on apps/client/src/router/index.js
> +    }
Effectivement

2023-04-07 14:47 UTC, this-is-tobi commented on apps/server/src/utils/exceptions.js
> +}
Je pense qu'on peut utiliser une simple fonction ? D'autant qu'on ne la customise pas ici, on ne fait que mettre un text dans une erreur standard j'ai l'impression ?

2023-04-07 15:05 UTC, LouisGongora commented on apps/server/src/utils/exceptions.js
> +}
C'est ça oui
Mais ça permet de faire `if (error instanceof UnauthorizedError)` afin d'envoyer un message d'erreur précis pour un cas précis

J'ai fait ça pour les test afin d'en avoir un avec les droits admin, et l'autre sans les droits admin

2023-04-07 15:28 UTC, clairenollet requested changes

2023-04-07 15:28 UTC, clairenollet commented on apps/server/src/controllers/admin/user.js
> +export const getUsersController = async (req, res) => {
Hello,
je pense que tu as moyen de bien simplifier tout ça !
on essaie de faire du fail fast : 

première ligne du try tu fais un `if (!req.session.user.groups.includes('admin')) throw new Error('Vous n'avez les droits administrateur')`
ensuite tu fais ton `getUsers`
et puis tu catch l'error et tu la renvoies telle quelle (pas besoin de classe)
:)

2023-04-10 16:44 UTC, this-is-tobi commented on apps/server/src/controllers/admin/user.js
> +export const getUsersController = async (req, res) => {
J'irais même un peu plus loin, avec quelque chose du style :
```js
try {
  if (! req.session.user.groups?.includes('admin')) {
    send500(res, 'Vous n\'avez pas les droits administrateurs')
    return
  }
  const users = await getUsers()
  req.log.info({
    ...getLogInfos(),
    description: 'Users successfully retreived',
  })
  send200(res, users)
} catch (error) {
  const message = 'Echec de récupération des utilisateurs'
  req.log.error({
    ...getLogInfos(),
    description: message,
    error: error.message,
  })
  send500(res, message)
}
```

Ce qui permet d'avoir l'erreur custom que tu voulais sans créer de classe et donc diminuer le nombre de lignes de code et globalement diminuer la complexité.

2023-04-13 15:53 UTC, clairenollet commented on apps/server/src/controllers/admin/user.js
> +      description: 'Users successfully retreived',
On met plutôt les messages en français :)

2023-04-13 15:59 UTC, clairenollet commented on apps/client/cypress/e2e/specs/sidebar.e2e.js
> +      // .getByDataTestid('menuAdministrationBtn').should('not.exist')
à suppr ?

2023-04-13 16:04 UTC, clairenollet commented on apps/client/src/stores/user.js
> +    }
Eventuellement pour gagner qq lignes : 

```js
if (isLoggedIn) {
  isAdmin.value = userProfile.value.groups.includes('admin')
}
```
Là tu attribue directement à `isAdmin` le retour du `includes` (`true` ou  `false`)

2023-04-13 16:12 UTC, clairenollet commented on apps/client/src/views/admin/ListUser.vue
> +}
On essaie de try catch les `await` dans le front :)
ex : 

```js
  try {
    await navigator.clipboard.writeText(generatedCI.value[key])
  } catch (error) {
    snackbarStore.setMessage(error?.message, 'error')
  }
```

2023-04-13 16:13 UTC, clairenollet commented on apps/client/src/views/admin/ListUser.vue
> +  await adminUserStore.getAllUsers().then(response => {
pas besoin de `.then` après un `await`.

Tu peux faire directement 

`allUsers.value = await adminUserStore.getAllUsers()`

2023-04-13 16:27 UTC, clairenollet commented on apps/client/src/views/admin/ListUser.vue
> +})
quand tu veux itérer et renvoyer le résultat tu peux faire un map, du genre

```js
const rows.value = allUsers.value?.map(element => ({
    firstName: element.firstName,
    lastName: element.lastName,
    email: element.email,
    createdAt: formatDate(element.createdAt),
    updatedAt: formatDate(element.updatedAt),
  }))
 ```

2023-04-13 16:27 UTC, clairenollet commented on apps/client/src/views/admin/ListUser.vue
> +})
ça te permet aussi de contrôler ce que tu mets dans tes `rows` (si jamais l'objet user change)

2023-04-13 16:30 UTC, clairenollet commented on apps/server/src/controllers/project.js
> +    const message = 'Projects non trouvés'
*Projets

2023-04-13 16:30 UTC, clairenollet commented on apps/server/src/controllers/project.js
> +      description: 'Projects successfully retreived',
plutôt en français

2023-04-13 17:04 UTC, clairenollet commented on apps/client/src/stores/user.js
>    const setIsLoggedIn = () => {
Tu peux éventuellement maj le TU du store correspondant : `apps/client/src/stores/user.spec.js`

2023-04-13 23:06 UTC, clairenollet submitted a review, later dismissed

2023-04-13 23:07 UTC, clairenollet reviewed
\

2023-04-24 17:38 UTC, this-is-tobi commented on apps/client/src/views/admin/ListUser.vue
> +}
Plutôt placer cette fonction dans `utils/date.js` ?

2023-04-24 17:40 UTC, this-is-tobi commented on apps/server/src/controllers/admin/user.js
> +import { getLogInfos } from '../../utils/logger.js'
Côté front on a un alias pour `src` qui est `@`, plutôt l'utiliser pour nos chemins d'import histoire de rester cohérent partout

2023-04-24 17:41 UTC, this-is-tobi commented on apps/server/src/controllers/project.js
> +}
Plutôt à déplacer dans `controllers/admin/project.js` (à créer)

2023-04-24 17:47 UTC, this-is-tobi commented on apps/client/src/views/admin/ListUser.vue
> +  }))
Ici on prend un warning `Invalid prop: type check failed for prop "rowData". Expected Array, got Object` parce que chacune de nos `rows` sont ici des objets (`rows`  étant un tableau d'objets), il faudrait ajouter un `Object.values(<notre_objet>)` pour convertir l'objet en tableau

2023-04-24 17:49 UTC, this-is-tobi commented on apps/client/cypress/e2e/specs/admin-users.e2e.js
> +})
Ouvrons le débat mais moi je partirais plus sur une refacto de ce style : 
```js
import { getUsers } from '../support/func.js'

describe('Administration users', () => {
  const users = getUsers().map(({ firstName, lastName, email }) => ({
    firstName,
    lastName,
    email,
  }))

  it.only('Should display admin users, loggedIn, is admin', () => {
    cy.kcLogin('tcolin')

    cy.visit('/admin/users')

    const values = []
    cy.get('tbody tr')
      .then($el => {
        $el.toArray()
          .forEach(row => {
            values.push({
              firstName: row.children[0].innerHTML,
              lastName: row.children[1].innerHTML,
              email: row.children[2].innerHTML,
            })
          })
      })
    cy.wrap(values).should('have.length', users.length)
    users.forEach(user => cy.wrap(values).should('deep.include', user))
  })
})
```

2023-04-25 08:39 UTC, this-is-tobi commented on apps/server/src/controllers/admin/user.js
> +import { getLogInfos } from '../../utils/logger.js'
Ah oui my bad j'avais lu `client`

2023-04-25 10:44 UTC, LouisGongora commented on apps/client/src/views/admin/ListUser.vue
> +}
En effet

2023-04-26 08:26 UTC, clairenollet commented on apps/client/src/router/index.js
> +  // If user not logged in & path not allowed for non logged user redirect to login
On met les commentaires fonctionnels en anglais alors ? (pas d'avis là-dessus)

2023-04-26 08:27 UTC, this-is-tobi commented on apps/client/src/router/index.js
> +  // If user not logged in & path not allowed for non logged user redirect to login
Ah désolé c'est mon côté international 💁🏻‍♂️, je modifie

2023-04-26 08:28 UTC, clairenollet commented on apps/client/cypress/e2e/support/func.js
> +}
pas possible d'importer la fonction `formatDate` de `apps/client/src/utils/date.js` ? Pour éviter de devoir maintenir les deux

2023-04-26 08:28 UTC, clairenollet commented on apps/client/src/views/admin/ListUser.vue
> +  'Courriel',
On utilise plutôt `e-mail` dans les autres pages, peut-être à harmoniser pour l'un ou l'autre

2023-04-26 08:29 UTC, LouisGongora commented on apps/client/src/router/index.js
> +  // If user not logged in & path not allowed for non logged user redirect to login
Vu qu'on a tous les noms de fonctions, etc en anglais, ce serait pas mieux d'avoir les commentaires fonctionnels aussi ?

2023-04-26 08:30 UTC, clairenollet commented on apps/server/src/controllers/admin/user.js
> +    sendServerError(res, error.message)
`sendNotFound` éventuellement (mais on va refacto les controllers de toute façon)

2023-04-26 08:51 UTC, clairenollet commented on apps/client/src/views/admin/ListUser.vue
> +  allUsers.value = await adminUserStore.getAllUsers()
manque un try catch ici avec snackbar en cas d'erreur (c'est un appel api) ?

2023-04-26 08:51 UTC, clairenollet commented on apps/client/src/views/admin/ListUser.vue
> +  await getAllUsers()
manque un try catch ici avec snackbar en cas d'erreur (c'est un appel api) ?

2023-04-26 09:15 UTC, this-is-tobi commented on apps/client/src/views/admin/ListUser.vue
> +  await getAllUsers()
Le `try/catch` est fait dans la fonction `getAllUsers()` du coup

2023-04-26 09:35 UTC, clairenollet approved these changes

2023-04-26 09:36 UTC, merged

2023-04-26 09:36 UTC, LouisGongora approved these changes